name: Validate Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Build Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
        env:
          CI: true
      
      - name: Check TypeScript
        run: npm run tsc --noEmit
        continue-on-error: true
